crack_repeating_key_xor: crack_repeating_key_xor.nim ../util/hex.nim ../1.3/single_byte_xor.nim ../1.5/repeating_key_xor.nim
	nim compile crack_repeating_key_xor.nim

clean:
	rm -rf nimcache crack_repeating_key_xor

.PHONY:
	clean
